name: "Nix Verification"
on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  verify:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            flake_attr: lukasz@linux
          - os: macos-latest
            flake_attr: lukasz@mac
    runs-on: ${{ matrix.os }}
    name: verify (${{ matrix.os }})
    timeout-minutes: 120
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            extra-substituters = https://nix-community.cachix.org
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: nix-community

      - name: Check Flake
        run: nix flake check --print-build-logs

      - name: Install Home Manager
        run: nix profile install .#home-manager

      - name: Build with Home Manager
        run: home-manager build --flake '.#${{ matrix.flake_attr }}'
